name: golden_test
description: "A utility Flutter plugin for writing golden tests that streamlines adding golden tests to your project"
version: 0.1.6
homepage: https://github.com/dmkasperski/golden_test
repository: https://github.com/dmkasperski/golden_test

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
